# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nlp',
                'doc_host': 'https://pvanhuisstede.github.io',
                'git_url': 'https://github.com/pvanhuisstede/nlp',
                'lib_path': 'nlp'},
  'syms': { 'nlp.discovering_topics': {},
            'nlp.pretrained_models': {},
            'nlp.spacy_ner': {},
            'nlp.word_embeddings': { 'nlp.word_embeddings.Corpus': ('word_embeddings.html#corpus', 'nlp/word_embeddings.py'),
                                     'nlp.word_embeddings.Corpus.__init__': ('word_embeddings.html#__init__', 'nlp/word_embeddings.py'),
                                     'nlp.word_embeddings.Corpus.__iter__': ('word_embeddings.html#__iter__', 'nlp/word_embeddings.py'),
                                     'nlp.word_embeddings.evaluate': ('word_embeddings.html#evaluate', 'nlp/word_embeddings.py')}}}