# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nlp',
                'doc_host': 'https://pvanhuisstede.github.io',
                'git_url': 'https://github.com/pvanhuisstede/nlp',
                'lib_path': 'nlp'},
  'syms': {'nlp.word_embeddings': {'nlp.word_embeddings.evaluate': ('word_embeddings.html#evaluate', 'nlp/word_embeddings.py')}}}