# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_pretrained_models.ipynb.

# %% auto 0
__all__ = ['en', 'text', 'doc_en', 'tokens']

# %% ../01_pretrained_models.ipynb 2
import spacy
en = spacy.load('en_core_web_sm')

# %% ../01_pretrained_models.ipynb 3
text = ("Donald John Trump (born June 14, 1946) is the 45th and former president of "
        "the United States.  Before entering politics, he was a businessman and television personality.")

print(f"Type of text: {type(text)}")
print(f"Length of text: {len(text)}")

# %% ../01_pretrained_models.ipynb 5
doc_en = en(text)

# %% ../01_pretrained_models.ipynb 6
list(doc_en.sents)

# %% ../01_pretrained_models.ipynb 7
print(len(list(doc_en.sents)))

# %% ../01_pretrained_models.ipynb 8
from IPython.display import display_html
import tabulate

tokens = [[t] for t in doc_en]
display(display_html(tabulate.tabulate(tokens, tablefmt='html')))
